Feature/5
Manraj45/soen390-team08 pull request #175
Opened 2021-04-03 18:01 UTC by davidthai0387

Closes #5 

![image](https://user-images.githubusercontent.com/45408503/113487235-f90e7400-9484-11eb-85a5-7d9e99e8ca6c.png)

Triggers page allows admins to activate/deactivate triggers. Trigger status is saved in the database. Email services will need to check which triggers are active before sending.

2021-04-03 18:40 UTC, Manraj45 commented on bike-erp/src/pages/Triggers/Triggers.tsx
> +      console.log(error.data);
Remove console log

2021-04-03 19:10 UTC, daniela-venuta requested changes

2021-04-03 19:10 UTC, daniela-venuta commented on bike-erp/backend/src/main/services/triggerService/TriggerService.ts
> +    // Retrive trigger state by ID
Can some comments be added about the valid trigger ids for people using the API?

2021-04-04 16:59 UTC, nasaku898 approved these changes

2021-04-06 22:48 UTC, Manraj45 requested changes
Everything seems good, but add guarding on backend endpoint (in triggers_routes) to restrict the roles that are not allowed to use the endpoints

2021-04-07 15:23 UTC, daniela-venuta approved these changes

2021-04-07 17:13 UTC, Manraj45 approved these changes
Good Job!

2021-04-07 17:15 UTC, merged